USE [master]
GO
/****** Object:  Database [BibliotecaDB]    Script Date: 11/15/2025 11:56:20 AM ******/
CREATE DATABASE [BibliotecaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BibliotecaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BibliotecaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BibliotecaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BibliotecaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BibliotecaDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BibliotecaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BibliotecaDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BibliotecaDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BibliotecaDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BibliotecaDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BibliotecaDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [BibliotecaDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BibliotecaDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BibliotecaDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BibliotecaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BibliotecaDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BibliotecaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BibliotecaDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BibliotecaDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BibliotecaDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BibliotecaDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BibliotecaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BibliotecaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BibliotecaDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BibliotecaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BibliotecaDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BibliotecaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BibliotecaDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BibliotecaDB] SET RECOVERY FULL 
GO
ALTER DATABASE [BibliotecaDB] SET  MULTI_USER 
GO
ALTER DATABASE [BibliotecaDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BibliotecaDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BibliotecaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BibliotecaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BibliotecaDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BibliotecaDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BibliotecaDB', N'ON'
GO
ALTER DATABASE [BibliotecaDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [BibliotecaDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BibliotecaDB]
GO
/****** Object:  Table [dbo].[Persona]    Script Date: 11/15/2025 11:56:21 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Persona](
	[PersonaID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[Apellido] [varchar](100) NOT NULL,
	[Cedula] [varchar](30) NULL,
	[Telefono] [varchar](20) NULL,
	[Email] [varchar](100) NULL,
	[Direccion] [varchar](200) NULL,
	[FechaRegistro] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PersonaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Rol]    Script Date: 11/15/2025 11:56:21 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rol](
	[RolID] [int] IDENTITY(1,1) NOT NULL,
	[NombreRol] [varchar](50) NOT NULL,
	[Descripcion] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[RolID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 11/15/2025 11:56:21 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[UsuarioID] [int] IDENTITY(1,1) NOT NULL,
	[PersonaID] [int] NOT NULL,
	[NombreUsuario] [varchar](50) NOT NULL,
	[ContrasenaHash] [varbinary](max) NOT NULL,
	[Salt] [varbinary](256) NOT NULL,
	[Estado] [bit] NOT NULL,
	[RolID] [int] NOT NULL,
	[FechaCreacion] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UsuarioID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Persona] ON 
GO
INSERT [dbo].[Persona] ([PersonaID], [Nombre], [Apellido], [Cedula], [Telefono], [Email], [Direccion], [FechaRegistro]) VALUES (1, N'Joel', N'Polanco', N'402-2912345-6', N'809-555-1122', N'joel.polanco@example.com', N'Santiago, RD', CAST(N'2025-11-14T11:21:06.610' AS DateTime))
GO
INSERT [dbo].[Persona] ([PersonaID], [Nombre], [Apellido], [Cedula], [Telefono], [Email], [Direccion], [FechaRegistro]) VALUES (2, N'María', N'Gómez', N'001-1567890-3', N'829-555-3344', N'maria.gomez@example.com', N'La Vega, RD', CAST(N'2025-11-14T11:21:06.610' AS DateTime))
GO
INSERT [dbo].[Persona] ([PersonaID], [Nombre], [Apellido], [Cedula], [Telefono], [Email], [Direccion], [FechaRegistro]) VALUES (3, N'Carlos', N'Ramírez', N'031-4478912-1', N'849-555-7788', N'carlos.ramirez@example.com', N'Santo Domingo, RD', CAST(N'2025-11-14T11:21:06.610' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Persona] OFF
GO
SET IDENTITY_INSERT [dbo].[Rol] ON 
GO
INSERT [dbo].[Rol] ([RolID], [NombreRol], [Descripcion]) VALUES (1, N'Administrador', N'Acceso total al sistema')
GO
INSERT [dbo].[Rol] ([RolID], [NombreRol], [Descripcion]) VALUES (2, N'Bibliotecario', N'Gestión de libros y préstamos')
GO
INSERT [dbo].[Rol] ([RolID], [NombreRol], [Descripcion]) VALUES (3, N'Usuario', N'Acceso básico para consultar')
GO
SET IDENTITY_INSERT [dbo].[Rol] OFF
GO
SET IDENTITY_INSERT [dbo].[Usuario] ON 
GO
INSERT [dbo].[Usuario] ([UsuarioID], [PersonaID], [NombreUsuario], [ContrasenaHash], [Salt], [Estado], [RolID], [FechaCreacion]) VALUES (1, 1, N'jpolanco', 0x8F4A8B0E96D5F55A33DE88371CB84F2A9A5F12D1B669C72F7A3A4B60C22D1479, 0xA3B1C4D5E6F708192837465564738291, 1, 1, CAST(N'2025-11-14T11:23:07.297' AS DateTime))
GO
INSERT [dbo].[Usuario] ([UsuarioID], [PersonaID], [NombreUsuario], [ContrasenaHash], [Salt], [Estado], [RolID], [FechaCreacion]) VALUES (2, 2, N'mgomez', 0x7B99C862DA13BC55F70810ACB188A99F54E7B112F14DE873C996CE227FA14C55, 0xB2C3D4E5F607182736455647382912A3, 1, 2, CAST(N'2025-11-14T11:23:07.297' AS DateTime))
GO
INSERT [dbo].[Usuario] ([UsuarioID], [PersonaID], [NombreUsuario], [ContrasenaHash], [Salt], [Estado], [RolID], [FechaCreacion]) VALUES (3, 3, N'cramirez', 0x6A77D229F3C4B97F55A1B8C2441F9D3398A7C11D44BEE67399ACF112DE90781F, 0xC1D2E3F4051625344657683921A3B4C5, 1, 3, CAST(N'2025-11-14T11:23:07.297' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Usuario] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Persona__A9D10534FED8ABEC]    Script Date: 11/15/2025 11:56:21 AM ******/
ALTER TABLE [dbo].[Persona] ADD UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Usuario__6B0F5AE0D6A5BED4]    Script Date: 11/15/2025 11:56:21 AM ******/
ALTER TABLE [dbo].[Usuario] ADD UNIQUE NONCLUSTERED 
(
	[NombreUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Persona] ADD  DEFAULT (getdate()) FOR [FechaRegistro]
GO
ALTER TABLE [dbo].[Usuario] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [dbo].[Usuario] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD FOREIGN KEY([PersonaID])
REFERENCES [dbo].[Persona] ([PersonaID])
GO
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD FOREIGN KEY([RolID])
REFERENCES [dbo].[Rol] ([RolID])
GO
USE [master]
GO
ALTER DATABASE [BibliotecaDB] SET  READ_WRITE 
GO
